development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: biscode_development
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: biscode_test
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

production:
  adapter: postgresql
  database: biscode_production
  pool: 5
